### ISSUE TITLE
mean column in /pip regional aggregates output 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#138]
Hi @tonyfujs,

Just spoke with Tefera who discovered that the mean is one of the values returned by PovcalNet for the regional aggregates, while it is not returned by PIP. Figuring that might be just be an omission in the code, but wanted to check whether it should be there or not. 

cc: @randrescastaneda 

![image](https://user-images.githubusercontent.com/8194990/138108796-41e42d0e-b8a9-4d3e-a5cf-47400e0d2d3d.png)

 https://github.com/PIP-Technical-Team/pipapi/blob/c443f6af53088b254d86a2040e57e74bb176e082/R/aggregate_by_group.R#L18

**Comment by randrescastaneda** [comment]
Yes, the mean should be returned. What should not be returned, at least for now, is distributional measures at the regional levels like the median or any other percentile. 
Best,
