### ISSUE TITLE
fs package not part of DESCRIPTON 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#14]
Should be imported if we intend to use this package for create file paths (currently used in TEMP-file)

**Comment by tonyfujs** [comment]
Thanks @Aeilert

This dependency should not be there. We can do without. I will remove it in a next iteration

**Comment by Aeilert** [comment]
Hi @tonyfujs, 

Not super important, but just letting you know that `{fs}` is now used within `pipapi:::clean_api_data()` without being listed in the Description. So use of the package fails unless the user manually installs `{fs}`.

**Comment by tonyfujs** [comment]
Thanks @Aeilert !
