### ISSUE TITLE
pip() fails when povline = NULL

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#20]
Not really that important, but `pip()` fails when povline is NULL, which is the default. 

The reason it fails is because `wbpip:::md_compute_poverty_stats()` has a threshold for `pov_status <- (welfare < povline_lcu)`. 

Setting povline to NULL does ofc not make a lot of sense, but I don't think the function should fail with its default arguments. We could for example set the default povline to 1.9 or modify the relevant code in `{wbpip}`. 

```r
> debugonce(wbpip:::md_compute_poverty_stats)
> pip(country = 'AGO', '2008', lkup = lkups, paths = paths)
  Error in rep(0, collapse::fsum(!pov_status)) : invalid 'times' argument
```

**Comment by tonyfujs** [comment]
Thanks @Aeilert 
`pip()` povline argument defaulting to 1.9 seems like the correct behavior here. Will update.
