### ISSUE TITLE
Change default branch to `dev` ? 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#211]
@tonyfujs : I wonder if we should change the default branch to `dev` since we now using that for main package development? That would make it easier to create PRs, wo/ accidently setting `master` as the base branch for the PR. 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by shahronak47** [comment]
Yes, it has benefits that helps in creating PR's and auto-closing the issues after branch has been merged. However, one drawback is that by setting the `dev` as default branch when you do `devtools::install_github("PIP-Technical-Team/pipapi")` it will install the package from `dev` and if the user needs the `master` version then they explicitly need to add `@master` in their `install_github` command. 

Is that what we want or ready to adjust? @tonyfujs

**Comment by tonyfujs** [comment]
mmm... Good point. Let's leave it as it then.
