### ISSUE TITLE
Rewrite parse_parameters()

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#241]
Query arguments are currently hard-coded. Very brittle to change. It would be nice to explore alternative ways of handling this.

For instance, if we add a new query parameter, it will never be picked by the `parse_parameter()` function until this function is being updated as well.

https://github.com/PIP-Technical-Team/pipapi/blob/04fb563c21f740f3232a7e1f28f829a2ccf79fce/R/utils-plumber.R#L138

**Comment by shahronak47** [comment]
I have an idea to use `type.convert` which will automatically guess the right class. This works really well. 

```
params <- list(
  country = "AGO",
  year = "2018",
  povline = "1.9",
  fill_gaps = "FALSE",
  aggregate = "FALSE",
  group_by = "none",
  welfare_type = "all",
  reporting_level = "all",
  popshare = "0.5",
  ppp = "1",
  format = "json"
)

type.convert(params, as.is = TRUE)

#$country
#[1] "AGO"

#$year
#[1] 2018

#$povline
#[1] 1.9

#$fill_gaps
#[1] FALSE

#$aggregate
#[1] FALSE

#$group_by
#[1] "none"

#$welfare_type
#[1] "all"

#$reporting_level
#[1] "all"

#$popshare
#[1] 0.5

#$ppp
#[1] 1

#$format
#[1] "json"
```

If you notice in the output numeric values like `year`, `povline` etc are automatically changed from chaarcter to numeric, logical values like `fill_gaps` and `aggregate` are automatically changed from character to logical. We can delete the `parse_parameter` function and simplify the `parse_parameters` function if we implement this. 

However, there is one problem though. According to our current code, we expect `year` variable to be of type character and not a number. May I know why is that so and is there a possibility to change that assumption?
