### ISSUE TITLE
Add rate limiting headers ?

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#245]
Would be good to have. And should help us reduce unintentional or intentional spam 

See [here](https://nordicapis.com/everything-you-need-to-know-about-api-rate-limiting/), [here](https://www.moesif.com/blog/technical/rate-limiting/Best-Practices-for-API-Rate-Limits-and-Quotas-With-Moesif-to-Avoid-Angry-Customers/)  or other source for best practice ideas.

**Comment by shahronak47** [comment]
Maybe explore https://github.com/tarakc02/ratelimitr

**Comment by shahronak47** [comment]
`ratelimitr` is a good option which allows us to rate limit requests from one user (one system) based on the conditions specified. 

Things to be considered - 

1. Would we like to implement this? 
2. If yes, then what would be a good rate limit that we would like to apply? 10 requests/minutes, 10 requests/second etc.
3. Do we want to rate limit only `pip` function or other functions as well? 

Another thing to think about is we probably would have to create a new function for rate limiting. To maintain backward compatibility the current `pip` would be changed to another name. 

```
pip_old <- function(country = "all",
                    year = "all",
                    .........
                    .........) {
..........
..........
}
```

and the new rate limiting function would be called as `pip` - 

```
pip <- ratelimitr::limit_rate(pip_old, ratelimitr::rate(n = 2, period = 60))
```

This will allow 2 requests every 1 minute from each user/system. 

I would continue researching on this and see if there are better solutions.

**Comment by shahronak47** [comment]
As discussed we will handle this at the infrastructure level and not on R level.
