### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#247]
Some of the queries are quite slow, and could use some optimization. This is particularly the case for requests that query ALL countries, ALL year, and request interpolated values.

**Comment by tonyfujs** [comment]
`pip(country = "all", year = "all", fill_gaps = TRUE, povline = 1.9, lkup = lkup)`

**Comment by shahronak47** [comment]
Part of optimisation in `wbpip` package https://github.com/PIP-Technical-Team/wbpip/pull/209
