### ISSUE TITLE
Add direct selection for PPP and data-version to handle the addition of new PPP vintage

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#265]

**Comment by tonyfujs** [comment]
My thoughts on this one is to keep things as they are at the pip() function level, and only modify what is exposed to end-users via the API, so we have something that would look like this:

- Request to the PIP API: `/pip?country=AGO&year=2008&povline=1.9&data-version=20220609&ppp-version=2011`

- Corresponding arguments to be passed to the pip function: `pip(country = "AGO", year = "2008", povline = 1.9, version = "
20220609_2011_02_02_PROD"`

- Behind the scene a function would transform the end-users arguments into the correct version ID. For instance: `create_folder_id(data-version = "20220609", ppp-version=2011)` would return "20220609_2011_02_02_PROD". This function would be used in one of the API filters

**Comment by shahronak47** [comment]
>Corresponding arguments to be passed to the pip function: pip(country = "AGO", year = "2008", povline = 1.9, version = " 20220609_2011_02_02_PROD")

Should we have a `version` argument in `pip()` call? I think we should not, right? We didn't had it previously. From the API we can directly pass the corresponding data to the `pip` call.

**Comment by tonyfujs** [comment]
> If `data-version` and `ppp-version` are not passed in the API, use the most recent version?

yes, calls were these parameters are not specified should default to the most recent version

**Comment by shahronak47** [comment]
> yes, calls were these parameters are not specified should default to the most recent version.

What happens when only one of the parameter is specified? I am still defaulting it to use the most recent version.
