### ISSUE TITLE
Improve region selection

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#266]
* Add unit tests for WLD selection
* Improve WLD selection. Currently, a selection of SSA, LAC, WLD fails

**Comment by shahronak47** [comment]
"WLD" doesn't work with `pip` ? It seems to work only with `pip_grp`. 

For example, 

```
#Doesn't work
pip(country = "WLD", year = "all", povline = 1.9, lkup = lkup)
#Empty data.table (0 rows and 40 cols): #region_name,region_code,country_name,country_code,reporting_year,reporting_level...


#Works
pip_grp(country = "WLD", year = "all", povline = 1.9, lkup = lkup)

    region_name region_code reporting_year reporting_pop poverty_line  headcount
 1:      CUSTOM      CUSTOM           1981    2369858509          1.9 0.84243399
 2:      CUSTOM      CUSTOM           1982    2408099013          1.9 0.82052474
 3:      CUSTOM      CUSTOM           1983    2446241182          1.9 0.78635040
 4:      CUSTOM      CUSTOM           1989    2265608505          1.9 0.67879914
 5:      CUSTOM      CUSTOM           1990    2280416205          1.9 0.66039108
.......
.......
```

Moreover, the selection of SSA, LAC, WLD works for me.  

```
pip_grp(country = c("WLD", "LLC", "SSA"), year = "all", povline = 1.9, lkup = lkup)

 region_name region_code reporting_year reporting_pop poverty_line  headcount
 1:      CUSTOM      CUSTOM           1981    2369858509          1.9 0.84243399
 2:      CUSTOM      CUSTOM           1982    2408099013          1.9 0.82052474
 3:      CUSTOM      CUSTOM           1983    2446241182          1.9 0.78635040
 4:      CUSTOM      CUSTOM           1989    2265608505          1.9 0.67879914
.......
.......
```

**Comment by tonyfujs** [comment]
> "WLD" doesn't work with `pip` ? It seems to work only with `pip_grp`.
> 
> For example,
> 
> ```
> #Doesn't work
> pip(country = "WLD", year = "all", povline = 1.9, lkup = lkup)
> #Empty data.table (0 rows and 40 cols): #region_name,region_code,country_name,country_code,reporting_year,reporting_level...

You're right. This seems to be a side effect of the last update that supports alternate aggregates. There is a new function called `create_country_vector()` and my guess is it does not handle `WLD` correctly.
If you look at the PROD site (that still runs the previous version of the API),  it handles `WLD` correctly for `pip`
https://api.worldbank.org/pip/v1/pip?country=WLD&year=2010&povline=1.9
cc @randrescastaneda

**Comment by tonyfujs** [comment]
> #Works
> pip_grp(country = "WLD", year = "all", povline = 1.9, lkup = lkup)
> 
>     region_name region_code reporting_year reporting_pop poverty_line  headcount
>  1:      CUSTOM      CUSTOM           1981    2369858509          1.9 0.84243399
>  2:      CUSTOM      CUSTOM           1982    2408099013          1.9 0.82052474
>  3:      CUSTOM      CUSTOM           1983    2446241182          1.9 0.78635040
>  4:      CUSTOM      CUSTOM           1989    2265608505          1.9 0.67879914
>  5:      CUSTOM      CUSTOM           1990    2280416205          1.9 0.66039108
> .......
> .......

`WLD` works with `pip_grp`, but not with the new `pip_grp_logic` function. This is also due to the new `create_country_vector` function.

@randrescastaneda Can you please take a look at `create_country_vector` and make sure it handle the `WLD` code correctly. It currently throws an error. Thanks!
