### ISSUE TITLE
Bug in /api/v1/get-cpi

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipapi#27]
The call  `/api/v1/get-cpi` fails with the error `<simpleError in sprintf("%s_aux/%s.fst", data_dir, table): object 'data_folder_root' not found>`

`data_folder_root` should probably be replaced by `lkups$data_root`

https://github.com/PIP-Technical-Team/pipapi/blob/14ca3cb0f1668724f10c8b9ecb2ffab71e82ce81/inst/plumber/v1/plumber.R#L79-L86

**Comment by tonyfujs** [comment]
Good catch. This has been addressed in a feature branch, and will be fixed on master once the PR is pushed and merged.
