### ISSUE TITLE
Update /aux endpoint to return data in long format

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#272]
Maybe by adding a parameter to the  `/aux` endpoint?

**Comment by shahronak47** [comment]
Is there a particular id column that we would like to keep? 

If yes, 
     Every aux table has different columns in them. Do we have a different id column for each dataset? In such case, do we have a separate code for each dataset. 

If no, 
    We would combine the complete dataset in two columns only (variable and value) which would mean their would be variable type mismatch in the value column. We would have mix of numeric, character, logical etc values.
