### ISSUE TITLE
Add new endpoint that returns metadata from the microdata library

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#34]
See Minh's email from 07/30/2021: Contains .xlsx and .do files to generate the correct table.

The creation of the metadata file should also be part of the pipeline. (I have the code that does the microdata harvesting, and we'll need to handle the part that was updated manually by Minh. This can wait for now.)

The endpoint should be very simple: Returns the full table, or single country if the country parameter is specified.

**Comment by Aeilert** [comment]
Hi @tonyfujs,

No .do file(s) (only .xlsx and .dta) in the email, so just wanted to check if we should take the current .xlsx as-is, or if you know which modifications should be made?

**Comment by tonyfujs** [comment]
Sorry, .dta indeed, no .do file. Please see Minh's explanation in the email I forwarded you. We can discuss more during today's meeting if needed.

**Comment by Aeilert** [comment]
Got it. Will take a closer look.
