### ISSUE TITLE
Add comparable spell information API response

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#35]
Currently, the `api/v1/pc-charts/` endpoint returns the comparability variable that provides information about the comparable spells as an integer. ITS needs the full comparability spell so they can display it in the UI tooltip. For instance:  

year | comparability | comparability_spell |
----|----|----|
2000 | 0 | 2000 |
2001 | 1 | 2001 - 2004 |
2002 | 1 | 2001 - 2004 |
2003 | 1 | 2001 - 2004 |
2004 | 1 | 2001 - 2004 |
2005 | 2 | 2005 - 2006 |
2006 | 2 | 2005 - 2006 |

I think the easiest way to do that is to:
1. Create the `comparable_spells` column at the pipeline level, `survey_means` file
2. It should be automatically available in the `pip()` calls. 
   It may not be so automatic as quite a bit of variable selection is done via hard-coding currently, but it should be straightforward enough

**Comment by Aeilert** [comment]
Pipeline outputs has been updated. Closing.
