### ISSUE TITLE
Add region_code to the api/v1/hp-countries endpoint

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#36]
This one should be quite straightforward. Good one to tackle first.

**Comment by Aeilert** [comment]
Hi @tonyfujs,

Two questions here: 

1. Should the column be renamed to `region_code` or use column name already in the dataset (`pcn_region_code` / `wb_region_code`)? 
2. I see that `ui_pc_charts()` is selecting `wb_region_code`, but shouldn't both functions/endpoints return PCN-regions? Ref homepage and current setup. 


![image](https://user-images.githubusercontent.com/8194990/128131667-e8afa371-f911-41f2-9824-adea323369da.png)

**Comment by tonyfujs** [comment]
> Hi @tonyfujs,
> 
> Two questions here:
> 
> 1. Should the column be renamed to `region_code` or use column name already in the dataset (`pcn_region_code` / `wb_region_code`)?  

I think it's probably better to use `region_code`. Since the PCN region names will soon be deprecated. This way we avoid renaming it later.

> 2. I see that `ui_pc_charts()` is selecting `wb_region_code`, but shouldn't both functions/endpoints return PCN-regions? Ref homepage and current setup.
> 
> ![image](https://user-images.githubusercontent.com/8194990/128131667-e8afa371-f911-41f2-9824-adea323369da.png)  

Good point. I guess it should be PCN regions.
