### ISSUE TITLE
Fix hard-coded years in ui_hp_stacked() function

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#398]
The `ui_hp_stacked()` function is used exclusively for querying data to display on the homepage main chart. This chart uses only a subset of available years, and the selection of those years is currently hard-coded in the function itself. This is problematic for two main reasons:
- That selection of years generally changes with each update.
- Changing the hard-coded years in the function will reset the cache for this function as a side effect 

We need to have a more robust mechanism for selecting those years. My first intuition would be to have the vector of selected years generated programmatically at the data pipeline stage, and then pass that vector to the function.

Other ideas for this? @randrescastaneda @shahronak47

**Comment by randrescastaneda** [comment]
Hey Guys, I temporarily solved this issue, but we have to think of a better solution. The main problem is that those years are selected discretionally. Yet, I'll discuss it with the GPID team and get back to you. For now, I think Tony's idea is the most plausible.
