### ISSUE TITLE
Fix path issue with endpoints.R

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipapi#91]
Currently, the `plumber.R` accesses the `endpoints.R` file via `system.file("plumber/v1/endpoints.R", package = "pipapi")`. This is problematic because it means that the API version cannot be selected by passing the `version` argument to the `start_api()` function

**Comment by Aeilert** [comment]
Closing. Passing the version folder to `start_api()` will work as long as each version folder contains both an `endpoints.R` and a `plumber.R` file. `v1/plumber.R` would then refer to to `v1/endpoints.R` etc.
